# Generated by Django 4.2.9 on 2024-01-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_file_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
